[phases.setup]
  nixPkgs = ['nodejs-18_x', 'nodePackages.typescript']

[phases.install]
  cmds = ["npm install"]
  only = ["package.json", "package-lock.json"]

[phases.build]
  cmds = ["npm run build"]
  only = ["src/", "tsconfig.json"]

[start]
  cmd = "node dist/index.js"
